openapi: 3.0.0
info:
  title: Fake Service
  version: 1.0.0
paths:
  /hello:
    get:
      description: Get a greeting
      parameters:
        - name: greeting
          in: query
          required: false
          schema:
            type: string
        - name: number
          in: query
          required: false
          schema:
            type: number
        - name: break_things
          in: query
          required: false
          schema:
            type: boolean
      responses:
        200:
          description: We responded
          content:
            application/json:
              schema:
                type: object
                properties:
                  greeting:
                    type: string
    post:
      description: Test body conversion
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                number:
                  type: number
        required: true
      responses:
        204:
          description: I heard you